server:
  port: 2020
spring:
  application:
    name: blog_system
  datasource:
    url: jdbc:mysql://192.168.43.128:3306/blog_system?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  redis:
    host:  192.168.43.128 # Redis服务器地址
    port:  6379 # Redis服务器连接端口
    password:  123456 # Redis服务器连接密码